# Generated by Django 3.2.16 on 2022-12-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='staticfiles/img/default_book_cover.png', upload_to='mediafiles/books_covers'),
        ),
    ]
