# Generated by Django 3.2.16 on 2022-12-08 00:40

from django.db import migrations, models
import m_library.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20221205_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, validators=[m_library.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=30, validators=[m_library.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=20, validators=[m_library.core.validators.validate_only_letters]),
        ),
    ]
