# Generated by Django 3.2.16 on 2022-12-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='../staticfiles/img/default_book_cover.png', upload_to='books_covers/'),
        ),
    ]
