# Generated by Django 3.2.16 on 2023-01-21 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(upload_to='books/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub'])]),
        ),
    ]
