# Generated by Django 3.2.16 on 2022-12-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221203_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='staticfiles/img/default.png', upload_to='mediafiles/avatars'),
        ),
    ]
