# Generated by Django 3.2.16 on 2022-12-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='avatar',
            field=models.ImageField(default='staticfiles/img/default.png', upload_to='mediafiles/avatars'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
