# Generated by Django 3.2.16 on 2022-12-08 00:40

from django.db import migrations, models
import m_library.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_libraryuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[m_library.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[m_library.core.validators.validate_only_letters]),
        ),
    ]
