# Generated by Django 3.2.16 on 2022-12-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221208_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='avatar',
            field=models.ImageField(default='../staticfiles/img/default.png', upload_to='avatars/'),
        ),
    ]
