# Generated by Django 3.2.16 on 2022-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20221210_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
